apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bXfswDPaUUaXjZAak7cZ1lp86QXo1syl60OXNB69+/pdMkrtgih12PckpsgCoRd+buDGOOPgTIACiLd6P/dfePKJTchq/4W7JWI=,iv:zvWTQ5otp4ZkRpO5bHrkCqgzOEm39TNJNSeDlhHLpJM=,tag:M8jdrwCIGovZA/VPmZ+kMg==,type:comment]
    #ENC[AES256_GCM,data:dt1IlRijyzU4pThOJt4kZFPOWNjCFw5AZk2w0BEBVhQe2Z9GpKcq1pqDlB35t8XicWD4jGq+HP2FlzEbyPHpn38=,iv:qiEn2j3lHE2onhRFQ3noeu1HVPeqFkHjJ//ir8K/IvU=,tag:Ft6ViIXedGmwetdOiNPt0A==,type:comment]
    secret_key: ENC[AES256_GCM,data:jNcUlRmuu8NxY0aev5OLiZIVuRAhLErd8DH6UgxZxO5p/8o8DaJi6saxw+O3NexmLwRGMXd0iAoh9OGdt8K/,iv:P90MpkLp/S6UyoUXE8ZrMnDdEIB2p0ng7D2Rt8tu3cw=,tag:j7reN24IjilLIwo0oCZh0Q==,type:str]
    #ENC[AES256_GCM,data:s+XCu10veNGyOU13O/gDMcz+PEJOH0cit6kp44L2X9BL5roqh4rImOo3qufx0t4+Z9hh/w==,iv:RQbmaofXh1FgaAZkO3IRH9Jn/XwnZbyGAzf2LGzia4M=,tag:fbSc4o3ptPyid/HskHpDFw==,type:comment]
    bootstrap_password: ENC[AES256_GCM,data:d5S+b3qRyq81LIPXe7WtngrrFQgF,iv:GMA4lrzcgFKt8q/Jo93p8FbgPvoo5+raQ/Q9KOmtdLE=,tag:NZzquaUwg2J5bZoNjm7uug==,type:str]
    #ENC[AES256_GCM,data:omlOg+Ib7DMPom+KO98rKTfNrfGCPg==,iv:T+2WK3O/nU11P4jspdJlwkbcEnrxubGuLkxssv3Ija8=,tag:V14m6OHSp4KDZPfKGgc8XA==,type:comment]
    bootstrap_email: ENC[AES256_GCM,data:JWBsaTSWlvAn1QilwA==,iv:E7zG7G9uoDsHwvOXXGKxUmpFtQk3uE5+p76q6h2zRHE=,tag:h+mJAkFOc4l6ynEmA8o7UQ==,type:str]
sops:
    age:
        - recipient: age19lq4dtrxd5qdwkr63gpy2qfwnttu3nxlrp9rxmu659nkt4d8ld7skwj6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ01MNnVFMGJ4NUhNdk1X
            ZTNHN3JiaGRrMEd2L0xiTVlTQlpxdDdMRHlnCmE5RCtqTVpaK21FSXhyT3l6VUt4
            YnRpN1E0VmtFK1dBQnVvUjNQMkZSb3cKLS0tIEx5T0c5NFhBVHQvOXJJQnZmWXN2
            c296UkZkOHF2QzJZSmRUaUwxZ0NmQzAKceqNHaTCjUL6Y4ARSfpoXL4SU0DShNnD
            0vyTZ0qbvgFLkq19ubKLq0N+RTky+oYDppPatjdNtMyqil/tUtGYaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T22:30:19Z"
    mac: ENC[AES256_GCM,data:oTvP23Q/HWbw4YD05alMl1YZ19PIlzrFJn656alqfrT1h8Ir4Q6uCBN4k9bAaoHnZ8tzLDrCqT9NebACKw44orGgHeNHrffiFzLxZZ1rG/2wUnPLYexmfj4ZxNsutLDcj8ttLsB/8Ys0dgOxIIpzO3EXbfO0X5Q2RIo7P09A4eY=,iv:QeDmWA6j7sy8sC/vsSiLLZ0qzhrBTW5ZO4DNVenZOX4=,tag:W3TcZNeVQMILIoJIdD8LWg==,type:str]
    pgp:
        - created_at: "2026-01-17T21:10:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxdOhYsagpprAQ/+PkIcEO/DGG75NOatrX3q5q5Jjb9qUKdOiH+ic1uDpggs
            5GHwE+X8nxJ7a2wW3gruCtDRZ7ZZ6cPdCeO9zvBWjmSEGVvViskBmLQOX6/VggLd
            K1788ZE39BU+TkgPpJLWjTMU4QYpANArBcWzHSf3IiVIr3TnMQll5ETvJUBFjmYY
            ABoCAOG4CC0Ulz0r0cUSaZmMCSUxNj4ObdQvU7HNWOQg3AFONhcpGYQc+9D5UOcL
            Ei359d3ZuZA7Vi2bejyYXedPxUc5HnpVb9S2QLpxKFBeWo8lnxobERjX1z2bF8aM
            iofYADzhpMew1g4AoGeTc+uqEqbJG0HFVCa0bknU5+y7IcFX3ac2/KVeZaG2LDft
            TlkpL7K5fUJ4wnunAL5BDWX3iUzqBJHxrwYYdFiqnfiuOE3mw1YxRgC4H3VPGM06
            1mC6/pb8MNvc7qGGx24vsAgDO7L8FACy2BzoUjZef82MIpUCzXUglgIUqOf1rhtR
            5uz7MGsBmLLEy9nse9s1fSWgXAmGRUrI8d8iAzoLIZb+dQEMdwWlgs7fZOF/MWmO
            VFefVL02QTTortDMiQYknNoxE60Iv9AiZjQVey11zeG50B/1FLrD1uJ+LSWrfV0l
            YneYTO28G9gWBYta2anhiI9XTX5bspO6M/rG3/EsOvZNh7FXAZv0rj6fGrF0AejS
            XgEI9Tg9wRlYXapofWQByFvxsFdKOdAeFAtZXXthMvDo/uu2aFAu6SmqSNkvnh5i
            8E+r2EswLnRLqs3KM01V4YrclL5o2nwo/g9SexRu2LsWsKLsu1+hDE/G+l1iE8o=
            =SfQI
            -----END PGP MESSAGE-----
          fp: 528CFD6EA653B5EC59B701F483219063F9FC4626
        - created_at: "2026-01-17T21:10:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA81p//ryl184AQ/8CYPV7T/ERobi1zV45hDo1rM2Kz61nUbK970PlYzsu8w/
            Ax93l+WW+tJYsNqOf+wZIoQslM/i9BI/Wond4owHotxOdjB3AVU4eGEixpYAT3LI
            xSKpYy2sc7ZckkOtbcn/LVYlIyvVDcpVA5aW4bGoS9ExKZHahhEVl426qbr5UxqK
            teDHUdVPM7j9B282n1l8Sqa5ceD4+d6tpy29oH7ww5G6zzWNx1nAmx5AMx9dbT7j
            5rckjGc0/twEEhsUe0o/NizX3dbMx5X3JcvjgTj8RDfltGWe8WcHHQM8orB4Obn3
            HHR1re+BYxipGSkwMFLbr/7FMCPPm5V6aBgit9I0FAjCSWAXYa8hPe2QrH85LG9N
            /V8b59za2sbXwSIzm+I38Iazm/YdFzzDfZ8cnp6rPlz7uH+GJ7LLFv13IjO1Mv14
            D5zFpeAJo+uImMdI1e9DH1Z9LRpa7HlD6sD9h1Mrf0X2mFgYdu6oWOaPLhyU3XEf
            FE1WWHIk+QwKfWK5a4OfJQmesLNuMLkKoY9SZoMDsLo+WhEdwmPVJAJo7QvUchkf
            TblJNxvUawPDuozfzdmlMbIi1bylQE89DqwEwPqEUPcC/0KpHGjUZoBj8Nfh8Xtd
            07IM3MtH6LafFQZ2wano0Pe+DMfrrxddEywIEFL5MyweernRucHJ7rWAQ4OqCC7S
            XgHmWIBZJN1PKGxjKIi4dNRQ5QxSla2xExlXqesSbHEdVl6MZaVPgTvHvyChEs3X
            R5WhfBXluDBRyefPyCQRrh3IOxynfqISAHXx+Qdp3ZEDhO8pfY++KnE02C+xt5c=
            =xzFM
            -----END PGP MESSAGE-----
          fp: EE213327AA06F51445BE63B5B4324BD440FD54E3
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
