oauth:
    clientId: ENC[AES256_GCM,data:roFuajN8r6nwRLsfj5Xcu8o=,iv:DybveGa+iEYV9suX1VvJH1At83NQB/WSof7e2urLz9M=,tag:ytFUsG6TWsGCkszYA9rRUQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:qo+fzVYLOT0oRpJfS58uZQDHev7GwfDv3Mpb3aGDaLKBHJIjWB7FEjGcaTyMKpMj/gyiHg9x84dPGB5RkA==,iv:C805o25pElz7yeq40q3KaQcKbgyaWNg2pMgsj35IxBI=,tag:Kiyo3fj/Dj9EnxRgunnEEw==,type:str]
sops:
    age:
        - recipient: age19lq4dtrxd5qdwkr63gpy2qfwnttu3nxlrp9rxmu659nkt4d8ld7skwj6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmdRQ1NoZUtlYkFxd1lS
            dWIvOVpaK3RmSG0zWERZcHVkWjltVm1JL21NCld0UFVlM21wTTRQdTBKU0h1Qksz
            UjBlb0pCa3VLN0l0c2MrMVNHWFczbDgKLS0tIGJHSXNxS3Mwcmdoc0RENS9XemE1
            QmNxajBiMmliM3hUY3NsdmxtUTk5aVkKYNlGZANRMo9LkW4Nh1f3hqap5ni7Vcrw
            aBQhwfeKXgau187JGASlmALnddd15BZdzze2Kt0piU5MuCFRRmVC+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T15:25:04Z"
    mac: ENC[AES256_GCM,data:HIoYlqdD02kctftvtNgOkXw9CrgkcuyVzaUqyHnriGP14jyvrA+S7LtJ9fuzejcHbdaVYZaoCiSEXLt1EL76XcUO9Up/Ayz990AtV65beUExYaYtixPlWVMAcIzi/dKnMTA8dILr8hvG2muxMbo++KpKZaaK9wFd6HktaG1xbA4=,iv:NRzqQBX8tc2ayos7tTSrbtiLFqcXMaMNfd1Bfogc59U=,tag:AP6h8Ae6Z19vdlEK/Y0jug==,type:str]
    pgp:
        - created_at: "2026-01-16T15:24:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxdOhYsagpprAQ//V8qUDWBBM7UxtghoPhlRXCDxYfS1rTPbe+hLJ1KATut2
            m0j+yIvskN1KHh+jVsF/hZvIHcnuFIR528af52wVnok+622l63H3ixDBspYSMgyx
            jr6661PHEBuheFZCuRhkfsTDWhPRvGrPCBuu/3NxULiDPYGR8o9SxhUMABbfuRk3
            GR3YQyoxhHSfclmB/OVAVrxUPhhSQxzT5rwLcnRc1F1v2bp4lkW0ln3HUAKDIcf8
            h3Z0opyo+mDiwYYei0gii+lCcYU/MvkI4nz0ZzdRfmlS3hSCYCyUjVfLxkWRMjcu
            KTQpsfF4vF5YGboA4DxTWWjHweHkJuGMq6NGpL9PBYfBoPmypGjRlL+VPkglSlXT
            tCBG2kY6grT+UNzJQbg04/gD1ezRZMuloyymOdEt5YkMTXvfi8mU1e34v/nspcC9
            51tDIoY+RIi62N0oFR3Ln5nwjLr+bb7pfkU+S9dlL6Z5cMAu1s9iau1M5nC48HOj
            X3ymsmEZ1u9DUu4bCnmK3UvKGFLCjenCjWt4KXDxDfSfw3VamwFUJstbnhaP1TxK
            GGmNq3ANqb5+aV4lgxS32LfNLhFpKowNSccMyPzYbgytFhTNdeLcUWYsr1qHqMfW
            lDdY2oEDgWnBsOV5t+JERoeJzROF07so6pZq7a/nTAHO4rQ4JehI7R2nK8w5fmbS
            XAGdTm6bHunH/m/gnjJPAKQLjHnVEIWSRSyA4+TFzp8znYbXZUUYg9rnbfSo/agm
            PHhEUcy29xyQ7e0ZeJlwfBO8J0wQEJlQbmqeGJMYCkl3ISYDcc7rVzrZV8Y0
            =/HhB
            -----END PGP MESSAGE-----
          fp: 528CFD6EA653B5EC59B701F483219063F9FC4626
        - created_at: "2026-01-16T15:24:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA81p//ryl184ARAAuEQBdbU5s3O/7E44JldrCjZHiYxSLSs6FvJwc0S/979r
            OJyeWWuNBfG3GWxeM5ttJ/HmPnlp5C0J0kH38+r3C8xmPI5RZmZiN5tw1HSyNFRw
            q/a6C9p2x3C7SUjIGE8NteRIRdqk65e3XUwBVoQQLLfWJlpFxi/A13y05Iy+W3Yn
            XawVmUO8tsg2infuLpB9m1zB8G2JYtrdeWUDNxXQO1XQRM93zhuHkMjgLSrRjnTR
            9iA6GAVUT0FrWeS9zkhRAmPLrPHCoUVOnamRlZGverevnQ5OEwGwRr024DD8/HAi
            D0YerBXW/Jf2YOnz/V3E4znMkN61OiJb2MsfaU+MOwJ6VzZoMRhWnyAbE+6mnYoy
            2zZ150Z6ZhcTjgb6dwsP4DI5FSAWXw4sULQ0cBDmXTm5N+7gnKBhUsYdravuYvrE
            6ckQ2ih1rFKugr7Nf0Jvej6eyheo1YjbhluXVnOfcu7mpDYNIknvmxgXZXM6mfNB
            /i47KWwNMSWs44naLLw35KfRmtBt5XOmcNFEe9lqycenyXnvvArIG+sPcSZ37ZuJ
            2huREjobtyxAyHLUv4QlRPKTQZg2KMyVlsBIqs+2x8MO3eJiIcTgBplQBd3WcjFZ
            Fc/ie4duiicUmAxJdZi6aOStvIUaTIfMljhXrNnYbd01GMxKbXNf7V5Kq/s2RazS
            XAH+2I8m/QH26ekeD1lZM6VqMGEEhyyvuBTBFURRy4r2AbTxw7FPws9ZjHZeFnHh
            rKYYJlDDjvLpq9lgdEeDfuhga+YzLc0RaIfTQw5iWU9Jg847K/2eweXTFAMM
            =1ywR
            -----END PGP MESSAGE-----
          fp: EE213327AA06F51445BE63B5B4324BD440FD54E3
    unencrypted_regex: ^(apiVersion|metadata|kind|type|namespace|name)$
    version: 3.11.0
