oauth:
    clientId: ENC[AES256_GCM,data:cTaj8Mz5rhsm49wjqOd0Dzg=,iv:GSOk25sxuSeNodZkcc7+LojKn3kROiRypZs9ThnQleE=,tag:p5cvolWrfz62kCJXpcdPjg==,type:str]
    clientSecret: ENC[AES256_GCM,data:6XVjJV7xJZztaVyQIm/+0GA/dUgb33TY+5g5NHEYLQyNU6WkCPlT9+GcuRKO+TC2aDQ70tQIcuDr2xvM3Q==,iv:LsGEX8+xVVcPeTgKg0BMIN/VJ0wNhylK7Pdpx70Lxvk=,tag:vbZ3BiLQTJjtbbPurr1M4w==,type:str]
sops:
    age:
        - recipient: age19lq4dtrxd5qdwkr63gpy2qfwnttu3nxlrp9rxmu659nkt4d8ld7skwj6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZENVZk9uYjV4d2FzY01S
            cGN3d2l3TlV4Rmo4dGtNRWdEZXNQN2xDNEYwCldDWmJpTm45S0QzSXpiS3AvOFh4
            TnBmWHpIckJoZTRNd1VEeEh4Rkx2d3MKLS0tIGZaV3pWK3BjazJCUXoyM3VJZmJS
            UW9GYS9qZlRBbjV2UjVuM0d3QVR2S2MKZB8rP9HWXBi33iVWGOKLkhsNP2PzfwkN
            0cBchST5BnAig66JorRH/NgT79zqqTprksrj416QPZj63+1yX5Y7rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:13:55Z"
    mac: ENC[AES256_GCM,data:Wu3ulv8slfAEuKbeD8MCh19UDov/ZSg93S95cpCCW7PHH9NRW5CRf/uem7jtZChN7yCTpB+HN/lr2Iqt3QAuY8L27JEwd16tg+36SykHG+KYh00LpLzqBKwR6Wan9fqTYffcBAjc/yIB8xbiitx8xkDR9SMv0U+nNMhSU2naAG0=,iv:/kyxC1shyvtd0C2P2zhNBJsCd1dTZzaYnzKCqXxFgt4=,tag:bHnQf12F7oHq7VKIup3k8A==,type:str]
    pgp:
        - created_at: "2026-01-16T16:10:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxdOhYsagpprAQ//bVNxX344MjoccZiDS+1L0cD1BQFWx1Yyu8hPVNi6o0g3
            cIZ8YkT03ac3CdhMsS7+fhB9VpUjSSv9lnT9kw7JjS0XODywGV2JlVTgJ0nKZNCf
            TNHiwLiBCd1dXYD1PsNOj4YRKgFzPAO/L2yDH9FIXMACI2Xlwt5Hjq5gXZ1WKBA9
            7xjgBtTanPTRbc8RE2psw6DhBHPJuA99ziAoT6vk/xE8sEmUx6CbAmZi/D7E6MXI
            YL6Yel0AwcpalmdQ9/I24RGLSRlW0MGDhiSpyTzJQecreHOXMMnE9TZqvYnRpNep
            ZfpYMWOFP/y2+PAIo8mZMijm/3ALZPlo9HGdzhuCFiDUQssbb7oALmRnaD53ODII
            2VkalBr/2XH605NtDbQnLsL/Acw2Zymeu7omXZSRnazKAKZ3H32Y90ko2er00YpB
            NwBX2CB8zXzPqqIOEjMWZGZQWI6h63ibJVktMHXGensUn/s/rfDgCnfw+7pkIxnq
            Ng9z3e+b1IWNxigfy2Qe9YQ2YngLjHKo6XwBSpQcLmFZICh6zX0nFCTULHNNg5Px
            2yDqLNLCsOjMD63cSTzrXrFRNxEgGJZwZplr+EoeKRq/EpwBcvDCuGT0VjVgd6YS
            twizhxjQkfifborGzF11KF3+NtjWGAnH60Wugsa5vnJpsTyWM6MLNxGfu21x8o7S
            XgF///t3F/sKjQZf2afUjtIYQt+l325Ca8hPeduRs/TJSBH2HHWb3mriu41SjWhg
            ebf+vro8B4+ErqqtpkCb2UGcFfF/E40qr1sF9QyEVxHWo6yL3qLzCByRf8rxWPk=
            =G02K
            -----END PGP MESSAGE-----
          fp: 528CFD6EA653B5EC59B701F483219063F9FC4626
        - created_at: "2026-01-16T16:10:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA81p//ryl184AQ//cNXreeUvekgm4YD/cUneqt/fU2W6o0+TtHkYvnLi2jLy
            fbWqKnEFwtlNrxARD7K1SsthB0xsqKERg8MvNOaDOhJ7gR4udF4pnOpJw3Q6vbNh
            Y0uAy1JjOrGsuuq0jSAO1AZZzwYxzSFHvf/zrPZ+PS88N+ERkMTO4ClMb77NmxAB
            fHoOomKp03UPINUUm5x7AgGuvfaqosj4Ybatl/pRzRJly5W8yxu/7u5CgQgY9CbD
            NmbEfvPQlSmsNBoHoZS93hWvkwZdgH2DNqNgHR22Z3T5w6mt399N3OTdLAbTUcy7
            6s8J0gT44RCP2XoD6HpQH7NxLfXK3Lia/Az4jFXn+1r5T9TsriLPPSam7LlB+bTR
            PT8QYhmOyGeOSJzqMy0nrVEI2KiPzReeU0EF95tGqcG0/F7eXVuQIVKuW1eJ40wa
            Pfm9rBmcSDEovmbRbyoMiycsuQ3OBHfaaynmL0XZpmiD0KQWb78gMvfVrNy5mqeZ
            QBCPurm8ERpRb/1ZdsbOYv04Xf1QCkEv32nXmdlxONTgI2Nt4esLwPGo1I95O1Tl
            O3Wx/EM5dldvJkFMTosBlBwfQFJLtPd76OdeN3ItyoH52o32ybK+5J040sDdx9ps
            dcgi4VNWNK9pg1uAbzQuofHBKme9zBR6dkyVRwXNoC4PLbHUorrUZW11dsyPic7S
            XgGOd457ry1Qieg5r2YmG90Ui5kJxTnCFNJ5TsRLGeHee2ErKwy8Cpp9SGEKd8wZ
            pSW9D7+drCm77iKRMsnj5wvGkylhzixcexlZgPOGRprap4ePIOm2U6yOEVvy97E=
            =+RKb
            -----END PGP MESSAGE-----
          fp: EE213327AA06F51445BE63B5B4324BD440FD54E3
    unencrypted_regex: ^(apiVersion|metadata|kind|type|namespace|name)$
    version: 3.11.0
